### ISSUE TITLE
корень

### ISSUE THREAD

**Issue by kmmorozov** [kmmorozov/py2023git#7]
корень

**Comment by thechiken** [comment]
после выполнения функции функция return не возвращает результат
костыльно сделал вывод внутри функции koren

**Comment by thechiken** [comment]
[исправил логику фукции koren](https://github.com/kmmorozov/py2023git/commit/cfa2637bcdf1875d2cd2e397e9d363fe26b0c086)
[исправил немного логику фукции koren](https://github.com/kmmorozov/py2023git/commit/3c37c85d0ee09a8937ae103a57aee8c52479db1e)
[закомментировал вывод результата koren в calculater.py](https://github.com/kmmorozov/py2023git/commit/c6eef8dbf71ba73719e02d39730f32b8b5685712)
